### ISSUE TITLE
Submit a translation

### ISSUE THREAD

**Issue by dajiuji** [gisellevonbingen/Minecraft-GravitationalModulatingAdditionalUnit#16]
[zh_cn.json.txt](https://github.com/gisellevonbingen/Minecraft-GravitationalModulatingAdditionalUnit/files/9894014/zh_cn.json.txt)
The json file cannot be uploaded. I changed it to txt. I don't know if it will affect it.

**Comment by gisellevonbingen** [comment]
Maybe it's ok.
Thanks for translation.
I will comment here when release new version that apply your file

**Comment by gisellevonbingen** [comment]
Looks good

![image](https://user-images.githubusercontent.com/44163945/198841163-70cae2f8-a1ba-4dfe-9664-85e6fa71e73d.png)
![image](https://user-images.githubusercontent.com/44163945/198841595-eda5c1c1-22ba-4377-98f1-89cd43bafe8d.png)

**Comment by gisellevonbingen** [comment]
New version released
https://www.curseforge.com/minecraft/mc-mods/gravitational-modulating-additional-unit/files
