### ISSUE TITLE
Needs an update to work with latest mekanism

### ISSUE THREAD

**Issue by WhitePhant0m** [gisellevonbingen/Minecraft-GravitationalModulatingAdditionalUnit#35]
Whenever a player uses the module, they get kicked, with [this error](https://mclo.gs/BZi1lfm) on server side.

NF: 21.0.151
Mek: 10.6.7
GravUnit: 5.2

**Comment by gisellevonbingen** [comment]
Fixed, Thanks for report.
Update to 5.3 version please.
